name: Python Unittests

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Run Unittests
      run: python -m unittest test/test_unittest.py

    - name: Notify on success
      if: success()
      run: echo "Unit tests passed successfully."

    - name: Notify on failure
      if: failure()
      run: echo "Unit tests failed."
