name: Testing with Pytest

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run Pytest and Generate Report
      run: pytest --junitxml=pytest-report.xml

    - name: Upload Test Results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: pytest-report.xml

    - name: Notify on success
      if: success()
      run: echo "Pytest passed successfully."

    - name: Notify on failure
      if: failure()
      run: echo "Pytest failed."
